language: php

sudo: false

env:
  global:
    - secure: "lzjvDwo2nNIvlJMPKNMjReoZiClCgp1PIKn2mQj8LuO1JRtlJfWCYH4paJ42u8btCkwytHtphZjB9A37p14b1vCl8RmRRVDT9K5PTJokVsMUDg0JCcUKNgDK3g2E2Rq5Siidg1EMomiHj2UcTCPNYH53kxxZFSN1pdYbQL3BMmsG+MpbmIF18+fkpz2JEx/fMVrrJVJxGWWm6uQB/3UuHI9ksdhDsS9N+X62I0R7lqpfsQ1AkwmrJv0AkWQ10ein0kHBdDhQM0ZLVNf7IfRohlRRQZ4AOzZ7Yja5pcquOV6zpqIzrWlXUsEcxEtKObOz3gR5v3N3q1SlL3G8N6PsdPZ9WIzqfk5B5rTkoAExRLNfB5dBtj5tRjTpn7DoI6ssVon9Gn0ype9WzpcqqKZzvWE/AzMTDEn3EqlZPgNA6rKFm60LNvGBocXksj3nmZSwwWmNbsYQSwiQU2cBxZ1fMW8+0Svk97zC0LESTPo+n3VDbbpiJ65v3FBbIdauyEfi+XSi4GFs/pngJ6Obv+zGUvwQrCUoiyZOfFqr8R+3Umn7EWhT4FIWA0oXOxK223GzRdoy0f1KhjSUUKD/BlhY+UuBxyeGGDrpH5dsexggxNWcGBKCZxUfCbejv1yyVFxm6NuIpKA12sfdvwxDjxuWyWzZalmJaML1IGCwtZJTxLw="
    - secure: "L3BqqRn7499D9Y2DqpwHsaN5RCiuHDb5fcS3lazJnVoQ49apAUrvWb5BAAISJjzAPQv5lNJIBP6spKQs7CW0kec+xb4Iqb416OVAwPzf2SNtchu8pViKsePhr1SYS9L0XBq5bFLmKDPhUefTaPoC0nLbq76XQFkdDc1Be/hDxSqFAiswV02pNv7B1Pd4G+IyqCxhtFLBOdcXB5rNbNNwmiq35JCL4iT0tHt76r0dVOVcwzFUq+NOILwOjRfRqFlGCELt57RBgccZevmx9Iht4j91AZV1o53+RxHuMvLraDHeBUYGzC4UQHFMgtmb5IyyoEB6RzlsLEOyBod9bfY2ZGohSEeRse7v7IAtm2GpjJlzsp46V757omgQ3KROkoNSqMAuMUcqfsZt00O65RlbyC0kloq/vD6rAwvUsvjmSn8jMiFlxwbCXiFE8dHuc2UBkLeLmw1ptII6+ljWhljg7Upf9WPepEi6vNVHsmYluUutA/cELm0OZadejQO2j4QKb0xfsz5Dfuvcyf8zN8ER1zQUWuNah1qAoUhCgsAbGgwiXXucl9BJkwjmPZdI9AEGS7BeW2KMDOKmqG7+vfYsLoFd07HV/6ikI7ai37wqtinHM69wVOG5+DD21pmsBleDEDv6YiVzRV7iGXxlJIti/+CYJs36WywcoPYvYDtkfPM="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: WITH_LOWEST=true
    - php: 5.5
      env: WITH_HIGHEST=true WITH_CS=true
    - php: 5.6
      env: WITH_LOWEST=true
    - php: 5.6
      env: WITH_HIGHEST=true
    - php: 7.0
      env: WITH_LOWEST=true
    - php: 7.0
      env: WITH_HIGHEST=true
    - php: 7.1
      env: WITH_LOWEST=true
    - php: 7.1
      env: WITH_HIGHEST=true WITH_COVERAGE=true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - source .travis/xdebug.sh
  - xdebug-disable
  - composer validate
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - if [[ "$WITH_LOWEST" == "true" ]]; then composer update --prefer-lowest --prefer-dist; else composer install --prefer-dist; fi

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - mkdir -p build/logs

script:
  - if [[ "$WITH_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --configuration=test/Unit/phpunit.xml; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-disable; fi

after_success:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/test-reporter --coverage-report=build/logs/clover.xml; fi

notifications:
  email: false
