language: php

sudo: false

env:
  global:
    - secure: "q92e8zyuFWPIg7J64GHdaHh9xiJ0seWYn/TWk+hW14EwEFJRFYx97SS6sYQAG7b2QdpeaI4c4jmVmCMniQH6aDTanODILFieFypddirTsSdwTmd5DQcAvnXvj6FnF8RU0fFsjcLpNBWnWtGeG9zeorlyYQzYIXZtYNX4yqfDBDYod6pFw/fJavbRdal4UBZVDQrWfKj8ei2O02cYtWPwlTacM99/QLF3h438NnG6T6uiWjQWGGQ2KmN90hCzviRHYsscsRyPRCfkW5qIsxrm4pRTEDHU/zmB9jFTGj8QDzhoMEm1947trVWxH9UGIQXYJLI40HQkOPXAGBByO+AAWkcOuy+SoubFsQJ63p1qmAFuxhsc+0pFVuC6Jl0K64SS6GxQOENXZpLMZ3Jbfc6EmtJeWjt8h73oEAMEz6QKPIV9zdSDITY1Gnms/QWZ5gUzvfqaGWxnF/jRUX7naTIJqAKELVQohHxhYlkYqv9p++tNlXogm6R+tTOPkN7WjGnKmu+B+DjsQg430VlajkkL8aTWqbzT5RuI5uNYCURz1++gVIZJrVpO+rdjuKVjCCLUevtuAEoq1LEe25oX3vvq6OnftWXhJlzaPDUg+/OA6CN4sXIeZ4n6IKSKg6C7JlmzVMHROLiG9P1x8ZeNG4xQUl5mKrsnN1Lm7dUkDpUONx8="
    - secure: "L3BqqRn7499D9Y2DqpwHsaN5RCiuHDb5fcS3lazJnVoQ49apAUrvWb5BAAISJjzAPQv5lNJIBP6spKQs7CW0kec+xb4Iqb416OVAwPzf2SNtchu8pViKsePhr1SYS9L0XBq5bFLmKDPhUefTaPoC0nLbq76XQFkdDc1Be/hDxSqFAiswV02pNv7B1Pd4G+IyqCxhtFLBOdcXB5rNbNNwmiq35JCL4iT0tHt76r0dVOVcwzFUq+NOILwOjRfRqFlGCELt57RBgccZevmx9Iht4j91AZV1o53+RxHuMvLraDHeBUYGzC4UQHFMgtmb5IyyoEB6RzlsLEOyBod9bfY2ZGohSEeRse7v7IAtm2GpjJlzsp46V757omgQ3KROkoNSqMAuMUcqfsZt00O65RlbyC0kloq/vD6rAwvUsvjmSn8jMiFlxwbCXiFE8dHuc2UBkLeLmw1ptII6+ljWhljg7Upf9WPepEi6vNVHsmYluUutA/cELm0OZadejQO2j4QKb0xfsz5Dfuvcyf8zN8ER1zQUWuNah1qAoUhCgsAbGgwiXXucl9BJkwjmPZdI9AEGS7BeW2KMDOKmqG7+vfYsLoFd07HV/6ikI7ai37wqtinHM69wVOG5+DD21pmsBleDEDv6YiVzRV7iGXxlJIti/+CYJs36WywcoPYvYDtkfPM="

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: WITH_COVERAGE=true
    - php: 7
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && "$WITH_COVERAGE" == "true" ]]; then COLLECT_COVERAGE=true; else COLLECT_COVERAGE=false; fi
  - if [[ "$COLLECT_COVERAGE" == "false" && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer validate
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - composer install --prefer-dist

before_script:
  - mkdir -p $HOME/.php-cs-fixer

script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --configuration phpunit.xml; fi
  - vendor/bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run

after_success:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then vendor/bin/test-reporter; fi

notifications:
  email: false
